{application,ueberauth,
             [{modules,['Elixir.Ueberauth','Elixir.Ueberauth.Auth',
                        'Elixir.Ueberauth.Auth.Credentials',
                        'Elixir.Ueberauth.Auth.Extra',
                        'Elixir.Ueberauth.Auth.Info',
                        'Elixir.Ueberauth.Failure',
                        'Elixir.Ueberauth.Failure.Error',
                        'Elixir.Ueberauth.Strategy',
                        'Elixir.Ueberauth.Strategy.Helpers']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,plug]},
              {description,"An Elixir Authentication System for Plug-based Web Applications"},
              {registered,[]},
              {vsn,"0.10.8"}]}.
