{application,hammer,
             [{modules,['Elixir.Hammer','Elixir.Hammer.Atomic',
                        'Elixir.Hammer.Atomic.FixWindow',
                        'Elixir.Hammer.Atomic.LeakyBucket',
                        'Elixir.Hammer.Atomic.TokenBucket',
                        'Elixir.Hammer.ETS','Elixir.Hammer.ETS.FixWindow',
                        'Elixir.Hammer.ETS.LeakyBucket',
                        'Elixir.Hammer.ETS.SlidingWindow',
                        'Elixir.Hammer.ETS.TokenBucket']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A rate-limiter with plugable backends."},
              {registered,[]},
              {vsn,"7.2.0"}]}.
