defmodule PhoenixKitEcommerce.CategoryAITranslatable do
  @moduledoc """
  `PhoenixKitAI.Translatable` adapter for shop categories (design §4.2).

  ## Resource identity

  `resource_type` is `"shop_category"`; `resource_uuid` is the category
  uuid.

  ## Fields

  `%{"name", "description"}` from the source language
  (`Translations.get/3` is deliberately NOT used — see `source_fields/2`),
  non-empty only. There is no `slug` in this map: like products, the slug
  is NEVER sourced from or trusted to the AI. Unlike products it isn't
  generated by hand here either — `Category.changeset/2` already builds
  per-language slugs via `LocalizedSlug.maybe_generate/2` on create, and
  this adapter calls that SAME shared function on its own changeset after
  merging (see "Slug" below), rather than reimplementing product's
  `slug_base`/`unique_slug` machinery.

  ## Concurrency

  All languages share ONE category row's JSONB maps, so `put_translation/4`
  re-reads the row under `FOR UPDATE` and merges against the latest
  committed state — the exact same locked-merge pattern
  `PhoenixKitEcommerce.AITranslatable` uses for products (the publishing
  group-adapter pattern), concurrent per-language jobs serialize on the
  row lock and never drop a sibling language.

  `update_category/2` / `update_category_translation/3` are deliberately
  NOT used here, and this is not a stylistic choice: `update_category/2`
  (`phoenix_kit_ecommerce.ex:4619`'s `update_category_translation/3` calls
  straight through to it) builds a changeset off the in-memory `category`
  argument and does a plain `repo().update/1` — no lock at all. Two
  concurrent language jobs (de and fr) on one category would each load the
  row, translate for ~45s, then write their own stale copy — the second
  write clobbers the first's language entirely. `merge_translation/4`
  below is this adapter's own `Repo.transaction` + `lock("FOR UPDATE")` +
  merge, built the same way `AITranslatable.merge_translation/4` is.

  ## Slug

  `Category.changeset/2` runs `LocalizedSlug.maybe_generate(:name)`
  (`category.ex:96`), but that changeset also runs full validation
  (`validate_localized_required`, `validate_no_circular_parent`, ...) that
  has no business running on a locked single-field merge. So this adapter
  builds its changeset with a bare `Ecto.Changeset.change/2` — same as the
  product adapter's write path — and then explicitly pipes it through
  `LocalizedSlug.maybe_generate(:name)` itself, since a bare `change/2`
  does not run that step on its own. `LocalizedSlug.maybe_generate/2`
  already only fills a BLANK per-language slug from that language's
  (possibly just-merged) name text and leaves an existing one untouched
  (write-once) — so unlike the product adapter there is no separate
  "which title text is true after this write" fallback to compute by
  hand: reading `get_field(changeset, :name)` after the merge already
  gives the right answer for both "title written this round" and "title
  write-narrowed away but a stored translation already exists".

  Slug uniqueness is enforced by the DATABASE, not app-side: V171's
  `phoenix_kit_shop_category_slugs` projection table (trigger
  `trg_shop_category_slugs`) carries a real pkey on (base language, slug
  value), which `Category.changeset/2` guards with
  `unique_constraint(:slug, name: "phoenix_kit_shop_category_slugs_pkey")`
  (`category.ex:99`). A bare `Ecto.Changeset.change/2` does not carry that
  declaration either, so this adapter attaches it itself before updating —
  without it, a same-language name collision would raise
  `Ecto.ConstraintError` out of `repo().update/1` instead of returning a
  changeset error the worker can discard as `persist_error`.

  ## Staleness / write-narrowing (design §4.1, §4.4)

  Identical model to products, built on the SAME shared
  `PhoenixKitEcommerce.TranslationFingerprint` module: `put_translation/4`
  decides, field by field, whether a translation is worth writing by
  comparing `opts[:source_fields]` against the CURRENTLY stored
  translation and fingerprint of the freshly-locked row, never against the
  possibly-stale `resource` argument. Resetting a category's fingerprints
  (`reset_reference/3`) is the only supported way to lift that protection
  ("перевести заново", design §4.4).

  ## Prompt

  Categories get their OWN prompt (`ensure_prompt/0`, slug
  `phoenixkit-shop-category-translation`) rather than sharing
  `phoenixkit-translate-content` (that slug belongs to
  `phoenix_kit_publishing`; repurposing it would mean changing another
  module's prompt format to save one database row). Built on
  `{{SourceFields}}` from day one — no literal-placeholder predecessor
  exists for this slug, so `ensure_prompt/0` ships with an empty
  `known_previous_shas` list; there is nothing to adopt.

  Requires the optional `phoenix_kit_ai` plugin: `ensure_prompt/0` returns
  `{:error, :ai_not_installed}` when it is absent, and the whole adapter is
  only reached through duck-typed discovery, which never runs without it.
  """

  # Structurally implements the `PhoenixKitAI.Translatable` behaviour, but we
  # DON'T declare `@behaviour` — phoenix_kit_ai is an optional dependency and a
  # declared behaviour would force it at compile time. Discovery is duck-typed
  # (`ai_translatables/0` + `PhoenixKitAI.Translatables`), so this module is
  # only ever exercised when the plugin is present; the guarded PhoenixKitAI
  # calls in ensure_prompt/0 are quietened for the plugin-absent build.
  @compile {:no_warn_undefined, PhoenixKitAI}

  import Ecto.Query, only: [where: 3, lock: 2]

  alias PhoenixKitEcommerce.Activity
  alias PhoenixKitEcommerce.Category
  alias PhoenixKitEcommerce.Events
  alias PhoenixKitEcommerce.LocalizedSlug
  alias PhoenixKitEcommerce.PromptRollout
  alias PhoenixKitEcommerce.TranslationFingerprint

  @resource_type "shop_category"
  @prompt_name "PhoenixKit Shop Category Translation"
  # MUST equal slugify(@prompt_name) — see AITranslatable's identical note
  # on why ensure_prompt/0 would fail every call after the first otherwise.
  @prompt_slug "phoenixkit-shop-category-translation"

  # No predecessor template for this prompt — it ships on {{SourceFields}}
  # from the start, so there is nothing to adopt (contrast with
  # AITranslatable.@known_previous_shas, which exists only because the
  # product prompt predates that scheme).
  @known_previous_shas []

  # field name in the prompt/pipeline => schema field. Identity for
  # categories (unlike products' "body" => :body_html), kept as an
  # explicit map rather than deriving one from the other so the prompt
  # vocabulary and the schema are free to diverge later without a rewrite.
  @field_map %{
    "name" => :name,
    "description" => :description
  }

  # The reverse of @field_map — write-narrowing looks a field up by its
  # SCHEMA name (the key `translated`, the AI response after clean/1, is
  # keyed by) but needs the PROMPT name to find that field's source text
  # in opts[:source_fields] (which is keyed the way source_fields/2 built
  # it — prompt vocabulary).
  @schema_to_prompt Map.new(@field_map, fn {prompt_field, schema_field} ->
                      {schema_field, prompt_field}
                    end)

  # Fingerprints are keyed by SCHEMA field name, the same identifier as
  # the JSONB column itself, so the candidate SQL
  # (TranslationFingerprint.select_candidates/2) can address both with one
  # `#{field}` interpolation.
  @schema_fields Map.values(@field_map) |> Enum.map(&Atom.to_string/1)

  @doc "The resource-type key this adapter registers under."
  def resource_type, do: @resource_type

  def fetch(@resource_type, category_uuid) when is_binary(category_uuid) do
    case repo().get(Category, category_uuid) do
      nil -> {:error, :resource_not_found}
      %Category{} = category -> {:ok, category}
    end
  end

  def fetch(_resource_type, _uuid), do: {:error, :resource_not_found}

  def source_fields(%Category{} = category, source_lang) do
    # Read the source language DIRECTLY, without Translations.get/3's
    # exact→default→first fallback: translating with the prompt saying
    # "from {{SourceLanguage}}" while feeding another language's text would
    # silently corrupt the result. Mirrors AITranslatable.source_fields/2.
    @field_map
    |> Enum.map(fn {prompt_field, schema_field} ->
      {prompt_field, Map.get(Map.get(category, schema_field) || %{}, source_lang)}
    end)
    |> Enum.filter(fn {_k, v} -> is_binary(v) and String.trim(v) != "" end)
    |> Map.new()
  end

  def put_translation(%Category{uuid: uuid}, target_lang, fields, opts)
      when is_binary(target_lang) do
    translated =
      for {prompt_field, schema_field} <- @field_map,
          value = clean(fields[prompt_field]),
          value != nil,
          into: %{} do
        {schema_field, value}
      end

    if translated == %{} do
      # Nothing usable came back from the caller at all (blank/absent
      # response) — a real error, distinct from every field being
      # write-narrowed away below (which is a success, not this).
      {:error, :no_translated_fields}
    else
      source_fields = Keyword.get(opts, :source_fields) || %{}

      case merge_translation(uuid, target_lang, translated, source_fields) do
        {:ok, {:written, updated}} ->
          Events.broadcast_category_updated(updated)
          log_translated(updated, target_lang, opts)
          {:ok, updated}

        # Design §4.4: every field was write-narrowed away (each one's
        # fingerprint still matched its stored translation) — success,
        # but the row didn't change, so no update event and no
        # activity entry.
        {:ok, {:skipped, current}} ->
          {:ok, current}

        {:error, _reason} = error ->
          error
      end
    end
  end

  @doc """
  "Перевести заново" (design §4.4): erases the stored fingerprints for
  `target_langs` × `fields` (schema field atoms; defaults to every
  fingerprinted field) under the same `FOR UPDATE` lock
  `put_translation/4` uses. The translated content itself is untouched —
  this only lifts write-narrowing's protection. Mirrors
  `AITranslatable.reset_reference/3`; see there for the full rationale.
  """
  @spec reset_reference(String.t(), [String.t()], [atom()]) ::
          {:ok, Category.t()} | {:error, term()}
  def reset_reference(uuid, target_langs, fields \\ Map.values(@field_map))
      when is_binary(uuid) and is_list(target_langs) and is_list(fields) do
    field_strings = Enum.map(fields, &Atom.to_string/1)

    repo().transaction(fn ->
      query = Category |> where([c], c.uuid == ^uuid) |> lock("FOR UPDATE")

      case repo().one(query) do
        nil -> repo().rollback(:resource_not_found)
        %Category{} = fresh -> apply_reset(fresh, target_langs, field_strings)
      end
    end)
  end

  defp apply_reset(%Category{} = fresh, target_langs, field_strings) do
    new_metadata = TranslationFingerprint.drop(fresh.metadata, target_langs, field_strings)

    case fresh |> Ecto.Changeset.change(%{metadata: new_metadata}) |> repo().update() do
      {:ok, updated} -> updated
      {:error, reason} -> repo().rollback(reason)
    end
  end

  @doc """
  "Проштамповать текущий источник как эталон" (design §4.1, §4.5). Mirrors
  `AITranslatable.stamp_reference/4` — see there for the full rationale:
  for every `{lang, field}` pair in `target_langs` × `fields` that
  currently HAS a stored translation, writes the current source's hash as
  its fingerprint, without calling the model and without touching the
  translation value. Runs under the same `FOR UPDATE` lock
  `put_translation/4` / `reset_reference/3` use.
  """
  @spec stamp_reference(String.t(), String.t(), [String.t()], [atom()]) ::
          {:ok, Category.t()} | {:error, term()}
  def stamp_reference(uuid, source_lang, target_langs, fields \\ Map.values(@field_map))
      when is_binary(uuid) and is_binary(source_lang) and is_list(target_langs) and
             is_list(fields) do
    repo().transaction(fn ->
      query = Category |> where([c], c.uuid == ^uuid) |> lock("FOR UPDATE")

      case repo().one(query) do
        nil -> repo().rollback(:resource_not_found)
        %Category{} = fresh -> apply_stamp(fresh, source_lang, target_langs, fields)
      end
    end)
  end

  defp apply_stamp(%Category{} = fresh, source_lang, target_langs, fields) do
    new_metadata =
      Enum.reduce(target_langs, fresh.metadata, fn lang, metadata ->
        field_hashes = stampable_field_hashes(fresh, source_lang, lang, fields)
        TranslationFingerprint.put_many(metadata, lang, field_hashes)
      end)

    case fresh |> Ecto.Changeset.change(%{metadata: new_metadata}) |> repo().update() do
      {:ok, updated} -> updated
      {:error, reason} -> repo().rollback(reason)
    end
  end

  # Only fields that have BOTH a non-empty source and an existing
  # translation for `lang` get stamped — see AITranslatable's identical
  # helper for the full rationale.
  defp stampable_field_hashes(%Category{} = fresh, source_lang, lang, fields) do
    for schema_field <- fields,
        source = fresh |> Map.get(schema_field, %{}) |> then(&(&1 || %{})) |> Map.get(source_lang),
        is_binary(source) and String.trim(source) != "",
        translation = fresh |> Map.get(schema_field, %{}) |> then(&(&1 || %{})) |> Map.get(lang),
        is_binary(translation) and String.trim(translation) != "",
        into: %{} do
      {Atom.to_string(schema_field), TranslationFingerprint.hash(source)}
    end
  end

  @doc """
  Design §4.3's candidate query for categories: categories with at least
  one field `:missing` or `:stale` (design §4.1) for a target language,
  hashed entirely in the database — see
  `PhoenixKitEcommerce.TranslationFingerprint.select_candidates/2`.

  Unlike `AITranslatable.candidates/3`, there is no status filter: design
  §4.3 explicitly excludes categories from `shop_translation_statuses` — a
  hidden category would otherwise ship translated navigation before it's
  visible.

  `opts`:

    * `:limit` — row cap (one row per `{uuid, language}` candidate
      pair, not per category).
  """
  @spec candidates(String.t(), [String.t()], keyword()) :: [
          %{uuid: String.t(), languages: [String.t()]}
        ]
  def candidates(source_lang, target_langs, opts \\ [])
      when is_binary(source_lang) and is_list(target_langs) do
    TranslationFingerprint.select_candidates(repo(),
      table: "phoenix_kit_shop_categories",
      fields: @schema_fields,
      source_lang: source_lang,
      target_langs: target_langs,
      statuses: nil,
      limit: Keyword.get(opts, :limit)
    )
  end

  @doc """
  Idempotently rolls out this adapter's translation prompt and returns its
  uuid — host forms pass it per job instead of the shared default prompt.
  See `AITranslatable.ensure_prompt/0` for the full rollout contract
  (`PhoenixKitEcommerce.PromptRollout`, design §5.2); this prompt has no
  predecessor to adopt, so `known_previous_shas` is empty.
  """
  @spec ensure_prompt() ::
          {:ok, String.t(), PromptRollout.sync_status()} | {:error, term()}
  def ensure_prompt do
    if Code.ensure_loaded?(PhoenixKitAI) and function_exported?(PhoenixKitAI, :create_prompt, 1) do
      PromptRollout.ensure(prompt_attrs(), @known_previous_shas)
    else
      {:error, :ai_not_installed}
    end
  end

  # -- internals ---------------------------------------------------------

  defp merge_translation(uuid, target_lang, translated, source_fields) do
    repo().transaction(fn ->
      query = Category |> where([c], c.uuid == ^uuid) |> lock("FOR UPDATE")

      case repo().one(query) do
        nil -> repo().rollback(:resource_not_found)
        %Category{} = fresh -> write_merged(fresh, target_lang, translated, source_fields)
      end
    end)
  end

  defp write_merged(%Category{} = fresh, target_lang, translated, source_fields) do
    {field_changes, fingerprint_updates, _written_fields} =
      narrow_writes(fresh, target_lang, translated, source_fields)

    if field_changes == %{} do
      {:skipped, fresh}
    else
      changes = maybe_put_metadata(field_changes, fresh, target_lang, fingerprint_updates)

      changeset =
        fresh
        |> Ecto.Changeset.change(changes)
        # Category.changeset/2 runs this step itself; a bare change/2
        # doesn't, so it's called explicitly here (see moduledoc "Slug").
        |> LocalizedSlug.maybe_generate(:name)
        # Category.changeset/2's own guard (category.ex:99) — a bare
        # change/2 doesn't carry it either, and without it a slug
        # collision raises Ecto.ConstraintError instead of returning a
        # changeset error the worker can discard.
        |> Ecto.Changeset.unique_constraint(:slug, name: "phoenix_kit_shop_category_slugs_pkey")

      case repo().update(changeset) do
        {:ok, updated} -> {:written, updated}
        {:error, reason} -> repo().rollback(reason)
      end
    end
  end

  # Design §4.4's write-narrowing table, applied per field against the
  # FRESHLY-LOCKED row (never the possibly-stale `resource` the worker
  # loaded before the multi-second AI call). Identical shape to
  # AITranslatable.narrow_writes/4, kept as a local copy rather than a
  # shared helper because the two adapters lock and merge different
  # schemas under different transactions.
  defp narrow_writes(fresh, target_lang, translated, source_fields) do
    Enum.reduce(translated, {%{}, %{}, []}, fn {schema_field, value}, acc ->
      apply_write_decision(fresh, target_lang, source_fields, schema_field, value, acc)
    end)
  end

  defp apply_write_decision(
         fresh,
         target_lang,
         source_fields,
         schema_field,
         value,
         {changes, fps, written}
       ) do
    prompt_field = Map.fetch!(@schema_to_prompt, schema_field)
    source = source_fields[prompt_field]

    existing_translation =
      fresh |> Map.get(schema_field) |> then(&(&1 || %{})) |> Map.get(target_lang)

    fp_field = Atom.to_string(schema_field)
    existing_fp = TranslationFingerprint.get(fresh.metadata, target_lang, fp_field)

    case TranslationFingerprint.write_decision(source, existing_translation, existing_fp) do
      :skip ->
        {changes, fps, written}

      {:write, new_fp} ->
        merged_field = Map.put(Map.get(fresh, schema_field) || %{}, target_lang, value)
        new_changes = Map.put(changes, schema_field, merged_field)
        # `new_fp == nil` (the caller passed no source for this field)
        # is recorded, not dropped: TranslationFingerprint.apply_writes/3
        # reads it as "erase this field's fingerprint". Leaving a stale
        # one behind is what makes a `:stale` field a permanent sweep
        # candidate — see that function's doc.
        new_fps = Map.put(fps, fp_field, new_fp)
        {new_changes, new_fps, [schema_field | written]}
    end
  end

  defp maybe_put_metadata(changes, _fresh, _target_lang, fingerprint_updates)
       when fingerprint_updates == %{},
       do: changes

  defp maybe_put_metadata(changes, fresh, target_lang, fingerprint_updates) do
    Map.put(
      changes,
      :metadata,
      TranslationFingerprint.apply_writes(fresh.metadata, target_lang, fingerprint_updates)
    )
  end

  defp clean(value) when is_binary(value) do
    case String.trim(value) do
      "" -> nil
      _ -> value
    end
  end

  defp clean(_), do: nil

  defp log_translated(%Category{} = category, target_lang, opts) do
    Activity.log("shop.category.updated",
      mode: "auto",
      actor_uuid: opts[:actor_uuid],
      resource_type: "category",
      resource_uuid: category.uuid,
      metadata: %{"target_language" => target_lang, "source" => "ai_translation"}
    )
  end

  # Built on {{SourceFields}} (phoenix_kit_ai §9.1) from day one — see
  # AITranslatable's identical block for why a fixed slot per field is
  # the defect this avoids (design §2).
  defp prompt_attrs do
    %{
      slug: @prompt_slug,
      name: @prompt_name,
      description: "Translates shop category fields (name, description) between languages.",
      content: """
      You are translating fields of an e-commerce category from {{SourceLanguage}} to {{TargetLanguage}}.

      RULES:
      - Preserve formatting exactly (line breaks, spacing, HTML if present).
      - Do NOT translate text inside code blocks, inline code, or URLs.
      - Translate naturally and idiomatically — commercial tone, natural for a shop.
      - Keep any HTML tags and attributes unchanged; translate only human-visible text.
      - Keep brand names, materials and measurements as-is unless they have a standard translation.
      - Output ONLY the structured markers below — no commentary, no preface, no closing remarks.

      The SOURCE section below has one marker per field of this category that
      needs translating — there is no fixed set of fields, so read whichever
      markers are actually present. For EACH marker in SOURCE, emit that
      SAME marker name back, followed by its translation:

          ---NAME---
          [translated name]

      Emit a marker for every field in SOURCE and no others — never invent
      a marker that wasn't there, and never skip one that was.

      === SOURCE ===

      {{SourceFields}}
      """
    }
  end

  defp repo, do: PhoenixKit.RepoHelper.repo()
end
