{application,ueberauth_google,
             [{modules,['Elixir.Ueberauth.Strategy.Google',
                        'Elixir.Ueberauth.Strategy.Google.OAuth',
                        'Elixir.UeberauthGoogle']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,oauth2,ueberauth]},
              {description,"ueberauth_google"},
              {registered,[]},
              {vsn,"0.12.1"}]}.
